### ISSUE TITLE
Фоновые задачи выполняются не в фоне, т.к. сервер не отдаёт ответ

### ISSUE THREAD

**Issue by Teclor** [beta-eto-code/bx.router#2]
https://github.com/beta-eto-code/bx.router/blob/d17f49c90f2caf27d86bf72616ae84609c476b80/lib/restapplication.php#L109
Почему здесь не используется $this->bitrixService->getBxApplication()->end(); ? внутри него и так вызывается terminate, но помимо этого происходит ещё один важный момент - отсылается ответ на запрос (внутри используется fastcgi_finish_request), в результате чего background jobs, запускаемые в terminate, запускаются действительно в фоновом режиме и не влияют на длительность формирования ответа на запрос.
Сейчас же ответ сервера формируется после окончания работы php-скрипта и его формирование может занимать в разы больше времени (например, если в background jobs у нас есть запросы к сторонним сервисам и ожидание ответов от них или долгие операции с БД), чем если бы использовался end, а не terminate.

**Comment by alex19pov31** [comment]
Спасибо, очень помогло.
